blank_issues_enabled: false
contact_links:
  - name: 💬 General Question
    url: https://github.com/Loki11Codes/Project-LiveFit/discussions
    about: Ask a question or share ideas with the community.
